#!/bin/bash
set -eu

NAMESERVER="8.8.8.8"
if [ ! -z "$1" ]; then
  NAMESERVER="$1"
fi

NAMESERVER2="8.8.4.4"
if [ ! -z "$2" ]; then
  NAMESERVER2="$2"
fi

echo "Setting nameserver to ${NAMESERVER} and ${NAMESERVER2}"
cat > /etc/resolvconf/resolv.conf.d/base <<EOF
# File generated by hap
nameserver $NAMESERVER
nameserver $NAMESERVER2
EOF
